# Generated by Django 3.1.14 on 2022-10-21 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0008_auto_20221021_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='next_evalution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_evalution', to='pokemon_entities.pokemon'),
        ),
    ]
