# Generated by Django 3.1.14 on 2022-10-21 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0009_pokemon_next_evalution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='next_evalution',
            new_name='next_evolution',
        ),
    ]
